version: "3"
services:
  web:
    name: MediaEngine
    image: alfg/nginx-rtmp:latest
    ports:
      - "1935:1935"
      - "8080:80"
    environment: 
      - STREAM_KEY_YOUTUBE
      - STREAM_KEY_FACEBOOK
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
